feature_descriptions = {
    'patient_id': 'Patient identifier code',
    'age_at_diagnosis': "Patient's age at diagnosis",
    'gender': 'Gender',
    'race': 'Race/Ethnicity',
    'source': 'Source dataset name',
    'mutated_genes': 'Mutated genes',
    'sample_type': 'Sample type',
    'stage_at_diagnosis': 'Localized or Metastatic stage',
    'tumor_size': 'Tumor size',
    'mitotic_rate': 'Mitotic rate',
    'primary_site': 'Primary tumor site',
    'metastatic_site': 'Metastatic site',
    'tumor_grade': 'Tumor grade assignment (cell appearance)',
    'treatment': 'Treatment name',
    'treatment_response': 'Treatment response',
    'treatment_start (treatment_duration_days)': 'Treatment start (treatment duration days)',
    'os_months': 'Overall survival in months',
    'os_status': "Patient's overall survival status",
    'ped_ind': 'Pediatric indication',
    'rfs_months': 'Recurrence-free survival in months',
    'pre_therapy_group': 'Clinical group before therapy',
    'ethnicity': 'Ethnicity',
    'msi_score': 'Microsatellite Instability (MSI) score',
    'msi_type': 'Microsatellite Instability (MSI) type',
    'tmb_nonsynonymous': 'Tumor Mutational Burden (TMB) nonsynonymous mutations',
    'age_at_seq_reported_years': 'Age at sequencing reported (years)',
    'note': 'Indicates if treatment is ongoing',
    'treatment_details': 'Indicates if there was drug therapy',
    'exon_number': 'Exon number',
    'primary_site_group': 'Primary tumor site group',
    'variant_type': 'Variant type',
    'loh': 'Indicates if the gene had loss of heterozygosity in the sample (LOH)',
    'year_of_diagnosis': 'Year of diagnosis',
    'derived_eod_t': 'EOD T parameter Extent of Disease ',
    'derived_eod_n': 'EOD N parameter Extent of Disease',
    'derived_eod_stage_group': 'Stage group according to the EOD manual Extent of Disease',
    'surgery_of_primary_site': 'Describes surgery at the primary tumor site',
    'scope_regional_lymph_surgery': 'Describes surgeries performed on regional lymph nodes',
    'surgery_of_other_site': 'Describes surgical removal of distant lymph nodes or other tissues or organs besides the primary site',
    'radiation_sequence_with_surgery': 'Sequence in which surgery and radiation were administered',
    'reason_no_cancer_directed_surgery': 'Reason for no surgery',
    'radiation_type': 'Type of radiation treatment',
    'systemic_sequence_with_surgery': 'Sequence in which surgery and systemic therapy were administered',
    'diagnosis_to_treatment_days': 'Time from diagnosis to treatment in days',
    'tumor_size_over_time': 'Tumor size over time (in mm)',
    'cause_specific_death': 'Indicates if the patient died of cancer',
    'other_cause_of_death': 'Indicates if the patient died from noncancer causes',
    'survival_months_flag': 'Indicates if it was possible to record survival months',
    'cod_to_site': 'Cause of death',
    'cod_to_site_icd_o_3': 'Cause of death in ICDO3 coding',
    'cod_to_site_icd_o_3_expanded': 'Cause of death in expanded ICD-O-3 coding',
    'vital_status': 'If the patient was alive when the study ended (vital status)',
    'year_of_follow_up': 'Year of last followup',
    'molecular_and_ihc_data': 'Molecular and immunohistochemistry data',
    'collection_date': 'Collection date',
    'MutationEffect': 'Mutation effect',
    'existing_variant': 'Indicates if the variant has already been cataloged and where'
}